---
- hosts: openunison_openshift
  tasks:
  - name: load unisonKeystore.p12
    register: secret_keystore
    command: "base64 -w 0  {{ local_dest_path }}/unisonKeystore.p12"

  - name: load openunison.yaml
    register: secret_openunison_yaml
    command: "base64 -w 0  {{ local_dest_path }}/openunison.yaml"

  - name: load ou.env
    register: secret_ou_env
    command: "base64 -w 0  {{ local_dest_path }}/ou.env"

  - name: generate secret
    template:
      src: "{{ local_src_path }}/openunison-secret.yaml.template"
      dest: "{{ local_dest_path }}/openunison-secret.yaml"
      mode: 0644

  - name: check if secret exists
    register: secret_exists
    command: "oc get secret -n {{ openunison_openshift_project_name }}"

  - name: delete existing secret
    command: "oc delete -f {{ local_dest_path }}/openunison-secret.yaml -n {{ openunison_openshift_project_name }}"
    when: "secret_exists.stderr == ''"

  - name: create new secret
    command: "oc create -f {{ local_dest_path }}/openunison-secret.yaml -n {{ openunison_openshift_project_name }}"

